[tool.poetry]
name = "twitter"
version = "0.1.0"
description = ""
authors = ["Rafael Almeida <rafael.almeida@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
gitpython = "^3.1.43"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"